### PR TITLE
Request for review (AuckLUG website)

### PR DESCRIPTION
**Pull request by KotaroW**
Hi,

Nice to meet you.

My name is Kotaro Watanabe, a new member to AuckLUG. I very much like the AuckLUG website and tinkered it so it is fitted in different screen sizes and on different devices. Cross-browser / cross platform tests were conducted (not exhaustive though, I tested on Ubuntu, Windows7, Android and iOS ). You'll find a little layout bug on Firefox for android (the bottom of the navigation menu is cut off a little bit, 5px or so ). This may be due to the fact that Firefox for android computes element sizes in a different way? Not so sure about it. I'll continue looking for a workaround anyway.

Should you need more information on the changes I'm suggesting, please let me know.

Have a good day,
Kotaro

### CODE REVIEW

**Comment by alxcenz** [comment]
Looks good to me.

**Comment by nelg** [comment]
looks good to me.  You happy to merge it alxcenz?

**Comment by alxcenz** [comment]
Sure am.

**Comment by KotaroW** [comment]
Thanks very much. I think I forgot to add a script tag to the head element... Can you advise me on which file to update?

**Comment by KotaroW** [comment]
I think I found it. 

_layouts/default.html

I'll add the script tag there and make another pull request.

**Pull request merged**
